import bootstrap from "@/app/library/bootstrap/list-sizes.json";

/**
 * The battle sizes a list can be built at.
 *
 * Two independent budgets, and a list has to satisfy both: `pointLimit` caps the
 * units, `detachmentPointBudget` caps how many detachments can be taken (several
 * are legal in 11th edition, which is why detachments carry a points cost at all).
 *
 * Sourced from `app/library/bootstrap/list-sizes.json`, which is hand-authored
 * like the rest of the library rather than generated by the parse pipeline.
 */
export interface ListSize {
    name: string;
    pointLimit: number;
    detachmentPointBudget: number;
}

export const listSizes: ListSize[] = bootstrap.listSize;

/**
 * Look up a size by name, or `null` if it is not one we know.
 *
 * Null rather than a default: a stored list naming a size that no longer exists
 * must surface as invalid, not quietly validate against the wrong budget.
 */
export function findListSize(name: string): ListSize | null {
    return listSizes.find((size) => size.name === name) ?? null;
}
